[tool.poetry]
name = "tsfminference"
version = "0.0.1"
description = "Service layer for TSFM granite models."
authors = ["IBM"]
license = "https://github.com/ibm-granite/granite-tsfm/blob/main/LICENSE"
packages = [{ include = "tsfminference/**/*.py" }]

[tool.poetry.dependencies]
# including 3.9 causes poetry lock to run forever
python = ">=3.10,<3.13"
numpy = { version = "<2" }
tsfm_public = { git = "https://github.com/IBM/tsfm.git", tag = "v0.2.6" }

# trying to pick up cpu version for tsfminference
# to make image smaller
torch = { version = ">2,<3", source = "pytorch" }

fastapi = { version = "*" }
pydantic = { version = "*" }
uvicorn = { version = "*" }

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
