[build-system]
requires = ["setuptools>=66", "wheel", "Cython"]

[project]
name = "tsfmservices"
requires-python = ">=3.9,<3.11"
version = "0.0.1"
authors = [{ name = "IBM" }]
description = "Services and notebooks for TSFM"
readme = "README.md"
license = { text = "Proprietary" }
classifiers = ["Private :: Do Not Upload"]

dependencies = [
    "pandas>=1.4",
    "scikit-learn",
    "transformers[torch] @ git+https://github.com/namctin/transformers.git@85baa5e",
    "tsevaluate @ git+ssh://git@github.ibm.com/srom/tsevaluate.git",
]

[tool.setuptools]
packages = ["tsfmservices", "tsfmservices.toolkit"]

[project.optional-dependencies]

notebooks = ["jupyter", "matplotlib", "datasets"]
testing = ["pytest", "tsfmservices[notebooks]"]
dev = ["pre-commit", "tsfmservices[testing]", "isort", "black[jupyter]"]
all = ["tsfmservices[notebooks,testing,dev]"]
ogv = ["datasets"]


# ###################################################
